### ISSUE TITLE
i have issue

### ISSUE THREAD

**Issue by Vortex853** [rwbutler/IPAUploader#2]
Showing Recent Messages

Build target ipa-uploader-cli of project ipa-uploader with configuration Debug

error: unable to resolve product type 'com.apple.product-type.tool' for platform 'iphonesimulator' (in target 'ipa-uploader-cli' from project 'ipa-uploader')

error: unable to resolve product type 'com.apple.product-type.tool' for platform 'iphonesimulator' (in target 'ipa-uploader-cli' from project 'ipa-uploader')

who can solved it

**Comment by rwbutler** [comment]
It looks as though you're attempting to run the command-line tool on an iPhone simulator which is not supported. IPA Uploader is a command-line tool for macOS.
